// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    messagingSenderId: '713856274307',
    projectId: 'wallpaper-selector',
    authDomain: 'wallpaper-selector.firebaseapp.com',
    storageBucket: 'wallpaper-selector.appspot.com',
    measurementId: 'G-WECD4PPQXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    messagingSenderId: '713856274307',
    projectId: 'wallpaper-selector',
    storageBucket: 'wallpaper-selector.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    messagingSenderId: '713856274307',
    projectId: 'wallpaper-selector',
    storageBucket: 'wallpaper-selector.appspot.com',
    iosClientId: '713856274307-qvd5ja8s0gi2cd1so7e4p5n4rfmn0sce.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallpaperSelector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    messagingSenderId: '713856274307',
    projectId: 'wallpaper-selector',
    storageBucket: 'wallpaper-selector.appspot.com',
    iosClientId: '713856274307-qvd5ja8s0gi2cd1so7e4p5n4rfmn0sce.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallpaperSelector',
  );
}
